---
abstract: 'A simple file cache for LibXML (CHI-based)'
author:
  - 'Maurice Mengel <mauricemengel@gmail.com>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-FileCache
requires:
  CHI: 0
  Digest::MD5: 0
  Moose: 0
  XML::LibXML: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=XML-LibXML-FileCache
  homepage: https://github.com/mokko/XML-LibXML-FileCache/wiki
  repository: git://github.com/mokko/XML-LibXML-FileCache.git
version: 0.001
